### ISSUE TITLE
Conceptos: Ceremonias, Artefactos y Roles (SCRUM)

### ISSUE THREAD

**Issue by nicocba93** [Ispc2022/grupoestudio1#1]
La primer tarea que se nos asignó es extraer del material de Scrum los siguientes conceptos: Ceremonias, Artefactos y Roles.
Registrar estos conceptos dentro del readme.md y renombrarlo como ConceptosScrum.md

**Comment by Ispc2022** [comment]
hola probando

**Comment by sidvicius96** [comment]
probando

**Comment by ccrrff2014** [comment]
hola
